### ISSUE TITLE
Pairing guide/competency files

### ISSUE THREAD

**Issue by deborahchua** [alphagov/gds-tech-learning-pathway#25]
We have a guide for [Pair/mob programming](https://github.com/alphagov/gds-tech-learning-pathway/blob/master/guides/pair-programming.md), and a competency [Taking the lead in a pairing situation](https://github.com/alphagov/gds-tech-learning-pathway/blob/master/career-path/competencies/taking-the-lead-in-a-pair-situation.md), both linked to from different roles.

I feel the competency file already includes the guide to pairing - maybe we only need one file?

**Comment by deborahchua** [comment]
@MatMoore I feel this is similar to the [issue you raised here](https://github.com/alphagov/gds-tech-learning-pathway/issues/11)

**Comment by MatMoore** [comment]
Yeah I agree, these could be merged. 👍 

Shall we just make it a competency? It feels like a combination of "skills, behaviours and knowledge" rather than a learning goal in itself.

If so, I'd change the title to be more broadly applicable, like we did with "producing production ready code".

The "taking the lead" part comes from the mid-level role, but working as part of a pair or mob still applies to juniors (even though we don't seem to mention pairing directly on the role description page).

**Comment by deborahchua** [comment]
After a bit more thought, I am wondering whether we should keep the competency as it is (just needs to be renamed), and change the guide so that it covers mobbing only. 

The competency covers pairing well, and I feel mobbing is just an extension to that and would make more sense as a guide? If this is the best approach, in the competency file we can link to the mobbing guide.

**Comment by MatMoore** [comment]
That could work too. I'm not really sure which is better yet. Will there be enough content in the guide to warrant it being separate?

I'm thinking that when we've got a few more guides that work well we can come up with a basic template for what a guide should look like.
