### ISSUE TITLE
Resource: well defined tasks

### ISSUE THREAD

**Issue by Davidslv** [alphagov/gds-tech-learning-pathway#40]
I believe that we should also cover what we mean with "well defined tasks" by providing examples, it's important that juniors have an understanding of what is a "well defined task" in order for them to know if the task is up to the standards before they pick it up and ending in a rabbit hole.
This is also valuable for developers (and seniors) who need to write "well defined tasks", by having examples it will gives us a standard on everyone's expectations of a "well defined task".

**Comment by MatMoore** [comment]
I think this article gives some good acceptance criteria for "well defined":

https://www.safaribooksonline.com/blog/2014/10/10/write-clearer-tickets-make-team-happier/

> The author of the ticket will be happier when they write a clear ticket because they know that they expressed their ideas.
The designer will be happier when they review the ticket for any design improvements they could offer.
The product manager will be happier when they refine the ticket and attach it to a larger set of work.
The project manager will be happier when they schedule the ticket and communicate its status to others.
The developer will be happier when they work on the change because it will be clear what you actually want the system to do (and not do).
The code reviewer will be happier when they review the code because they understand the wider context.
The QA team will be happier when they review the ticket because they understand the initial thinking, the known exceptions, and the primary business goal.
The future team will be happier when they need to understand what in the world we were thinking when we decided to do this.

On my team we have a [template](https://trello.com/c/6yeJZBNP/140-story-template) which works pretty well. If the template isn't filled out, the story is probably not well defined yet.

**Comment by Davidslv** [comment]
That's indeed a good reading.
I've copied your template and added "Applications involved" as I've found that important to have.
I also think we should add that if a person doesn't find the story clear it should ask for clarification  to a member of the team before starting it.

```markdown
# User need
As a
I want
So that

# What
Explanation of what this story is

# Why
Explanation of why we're doing this work

# Measurement
Is there a way of measuring the effect of this work?

# Who knows about it
Name the people in the team (or others teams) that know about this work

# Impact for users or other teams
Is there an impact for users that we need to communicate? Is there an impact for any other teams that we need to communicate?

# Related support tickets
Link to related zendesk ticket if this is a support story.

# Applications involved

List the name of the applications involved in this story
```

**Comment by deborahchua** [comment]
@Davidslv I have created a new resource for the user story template in this PR:
https://github.com/alphagov/gds-tech-learning-pathway/pull/48
